version: '3.8'

services:
  backend:
    image: eateasy-backend:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/eat_easy?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - eat-easy-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  frontend:
    image: eateasy-frontend:latest
    ports:
      - "80:80"
    networks:
      - eat-easy-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eat_easy
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - eat-easy-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  eat-easy-network:
    external: true

volumes:
  db_data:
