version: "3.8"

services:

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eat_easy
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - eat-easy-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


  backend:
    image: eateasy-backend:latest   # Use registry version if multi-node swarm
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/eat_easy?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
    networks:
      - eat-easy-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 5s


  frontend:
    image: eateasy-frontend:latest   # Use registry version if multi-node
    ports:
      - "80:80"
    networks:
      - eat-easy-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 5s


networks:
  eat-easy-network:
    external: true     # VERY IMPORTANT since created manually by Jenkins

volumes:
  db_data:
